CREATE TABLE ESTADO (
  IBGE INTEGER NOT NULL,
  SIGLA VARCHAR(2) NOT NULL,
  NOME VARCHAR(30) NOT NULL,
  AREA FLOAT NOT NULL,
  PRIMARY KEY IBGE
);

CREATE TABLE CIDADE (
  IBGE INTEGER NOT NULL,
  NOME VARCHAR(30) NOT NULL,
  AREA FLOAT NOT NULL,
  UF_PK INTEGER NOT NULL,
  PRIMARY KEY IBGE
);

ALTER TABLE CIDADE 
  ADD CONSTRAINT UF_fk FOREIGN KEY (UF_PK) REFERENCES ESTADO (IBGE);

